-- Offers
CREATE TABLE offers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    model_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    created_by INT NOT NULL,
    status ENUM('active', 'sold', 'removed') DEFAULT 'active' NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    production_year INT NOT NULL,
    odometer INT NOT NULL,
    fuel_type ENUM('petrol', 'diesel', 'electric', 'hybrid') NOT NULL,
    transmission ENUM('manual', 'automatic') NOT NULL,
    color VARCHAR(50),
    displacement INT,
    horsepower INT,
    torque INT,
    body_type ENUM('sedan', 'hatchback', 'suv', 'coupe', 'convertible', 'wagon', 'van', 'pickup') NOT NULL,
    doors_amount INT,
    seats_amount INT,
    vin VARCHAR(17) UNIQUE,
    registration_number VARCHAR(15),
    country_of_origin VARCHAR(100),
    is_accident_free BOOLEAN,
    is_first_hand BOOLEAN,
    is_used BOOLEAN,
    has_warranty BOOLEAN,
    has_service_book BOOLEAN,
    FOREIGN KEY (model_id) REFERENCES models(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);